### ISSUE TITLE
pytest on graphing fails with `pyvis==0.3`

### ISSUE THREAD

**Issue by himoto** [biomass-dev/biomass#200]
Hi @formersbach,
I noticed that [pytest on graphing](https://github.com/biomass-dev/biomass/blob/master/tests/test_text2model/test_graph.py) fails with the latest stable pyvis ([version 0.3.0](https://github.com/WestHealth/pyvis/releases/tag/v0.3.0)).
When I restrict pyvis version via `pyvis>=0.2.1,<0.3`, we don't see any errors.
Some updates in pyvis from v0.2 to v0.3 might affect the graph generation.

**Comment by himoto** [comment]
Thanks @formersbach! There is no rush.

**Comment by formersbach** [comment]
Hey @himoto !
It is indeed a change in pyvis that leads to the error. To be specific [this commit](https://github.com/WestHealth/pyvis/commit/fb20dd34dae42051d3a9f192a2a604aa0a299f04).
Pyvis now generates some temporary files but is unable to remove them since they're not generated at the expected location.
Should I attempt fixing it or do we just require pyvis v0.2?

**Comment by himoto** [comment]
Hi @formersbach,thanks for finding out the cause of the error.
I have added  a constraint that pyvis version must be smaller than 0.3 (#201, see below)and it works perfectly fine.
So far we can go with this but if we get a new problem regarding graph visualization, we will need to fix it to be compatible with the latest pyvis.

https://github.com/biomass-dev/biomass/blob/b7d2f13d9bdb2d9d00b1a3bcc0e848496608f80e/setup.py#L66

**Comment by formersbach** [comment]
Sounds good!
Shall we then close this issue?

**Comment by himoto** [comment]
Closed
